language: node_js

cache: 
  directories:
    - node_modules
    - ~/.npm

# Version del lenguaje
node_js:
  - '12'

git:
  depth: 3

script:
  - npm run build

deploy: 
  provider: pages # github pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN # Variable de entorno de travis ci - se debe generar en github en "developer settings" -> "personal access tokens" 
  local-dir: dist/ # ruta donde estan los archivos de produccion
  target_branch: gh-pages # esta es para github-pages. pero puede ser cualquier rama
  commit_message: "Deploy del proyecto" # Travis hace un commit en el target branch al hacer el deploy
  on:
    branch: master # Este script se ejecutara cuando hayan cambios en esta rama

